### ISSUE TITLE
Clock sync / CORS issue with Live-Clear DASH stream

### ISSUE THREAD

**Issue by joeyparrish** [Axinom/dash-test-vectors#16]
The Live-Clear DASH stream below has a CORS issue:

https://akamai-axtest.akamaized.net/routes/lapd-v1-acceptance/www_c4/Manifest.mpd

It contains UTCTiming reference to Manifest.mpd, but the necessary `date` header is inaccessible cross-origin, so a web-based player is unable to use this for clock sync.

```xml
  <UTCTiming schemeIdUri="urn:mpeg:dash:utc:http-head:2014" value="Manifest.mpd" />
```

The server is currently returning the header: `Access-Control-Allow-Headers: origin,range,hdntl,hdnts`.  This should include `date` as well.

**Comment by sandersaares** [comment]
I suspect this is a side-effect if #17 since I do see the header in the configuration file but it is indeed not being emitted. Presumably because the stream is down. Will take another look when the stream is back up.

Thanks for reporting!

**Comment by sandersaares** [comment]
Looks like my theory was wrong and this is indeed a defect - the stream is back up and the required header does not have the right value. We will adjust the settings shortly to correct this.

**Comment by sandersaares** [comment]
The CDN configuration has been updated to correct the headers. The `date` header is now part of `Access-Control-Expose-Headers`. Please feel free to close the issue if it looks good from your end.
