### ISSUE TITLE
Live streams are unavailable (HTTP 403)

### ISSUE THREAD

**Issue by joeyparrish** [Axinom/dash-test-vectors#17]
The live streams listed at https://github.com/Axinom/public-test-vectors#live-clear are unavailable.  Both of these give me an HTTP 403 error:

 - https://akamai-axtest.akamaized.net/routes/lapd-v1-acceptance/www_c4/Manifest.mpd
 - https://akamai-axtest.akamaized.net/routes/lapd-v1-acceptance/www_c4/Manifest.m3u8

**Comment by sandersaares** [comment]
We are in the process of performing some infrastructure upgrades - I expect the streams to be back up within a week.

**Comment by sandersaares** [comment]
This should now be fixed and the streams up and running in stable configuration once more. Please let me know if it looks good from your end @joeyparrish

**Comment by joeyparrish** [comment]
Looks good!  We have re-enabled the affected streams in the Shaka Player demo ([nightly build](https://nightly-dot-shaka-player-demo.appspot.com/demo/)).
