### ISSUE TITLE
ClearKey server SSL certificate expired

### ISSUE THREAD

**Issue by iququ** [Axinom/dash-test-vectors#22]
Hi, it seems the SSL certificate of the ClearKey server got expired.
The license server URL is https://drm-clearkey-testvectors.axtest.net/AcquireLicense.
And curl returns the following error message:
`curl: (60) SSL certificate problem: certificate has expired`
Could you update the server certificate? 

Thanks and Best Regards,
Daniel

**Comment by AxinomSupport** [comment]
Hi @iququ,

We have a new clear key License server URL now. Please use https://clearkey.axtest.net/AcquireLicense URL instead of the old one (https://drm-clearkey-testvectors.axtest.net/AcquireLicense) . 

Thank you.
