### ISSUE TITLE
403 response for V10 license requests

### ISSUE THREAD

**Issue by glennguy** [Axinom/dash-test-vectors#24]
Hi there

As the title suggests, I'm now getting a 403 response for the V10 samples where they were working before. This can be also be confirmed in the test player here https://reference.dashif.org/dash.js/nightly/samples/dash-if-reference-player/index.html. Do the header/token files need to be updated?

**Comment by AxinomSupport** [comment]
Hi @glennguy,

We have fixed the V10 samples now and you can use them now without an issue.

Thank you.
