### ISSUE TITLE
Playready DASH Live Test Stream with Key Rotation 

### ISSUE THREAD

**Issue by sivarajendranaidu** [Axinom/dash-test-vectors#5]
Could you please provide any test asset with Playready DASH LIVE with Key Rotation enabled.
Thanks and Regards,
Rajendra

**Comment by KristjanJ** [comment]
Hi!

Could you specify which key rotation is desired in this context - traditional or scalable?

Kristjan

**Comment by sivarajendranaidu** [comment]
Hi Kristjan
Thanks a lot I am looking for both hierarchical key rotation and non-hierarchical key rotation Playready LIVE Stream.
Thanks and Regards,
Rajendra

**Comment by KristjanJ** [comment]
Hi Rajenda!

We currently do not offer any live test streams or scalable (hierarchical) PlayReady key rotation.

However, we do support traditional key rotation of course. The closest test content you can currently find is this v7-MultiDRM-MultiKey-MultiPeriod - the key rotates after the 12 minute mark.

I will leave this issue open for now. We'll add test content where the key rotates more frequently and we'll also look into the live content request.

Kristjan
