### ISSUE TITLE
Axinom SSL cert will stop working in Chrome 70

### ISSUE THREAD

**Issue by joeyparrish** [Axinom/dash-test-vectors#6]
I just noticed this message in the JS console of Chrome 68:

> The SSL certificate used to load resources from https://media.axprod.net will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.

It's easy to reproduce in Shaka Player with this URL:

https://v2-4-4-dot-shaka-player-demo.appspot.com/demo/#asset=https://media.axprod.net/TestVectors/v7-MultiDRM-MultiKey-MultiPeriod/Manifest.mpd;lang=en-US;build=uncompiled;play

You may need to click the giant "play" button due to autoplay restrictions imposed by the browser.

**Comment by sandersaares** [comment]
Thank you for the notice. I am surprised to see we still have Symantec certs in use! This will be corrected shortly.

**Comment by sandersaares** [comment]
And this should now be fixed. Please let me know if you still see any lingering issues.

**Comment by joeyparrish** [comment]
Thank you!
